import type { CanvasElement } from '@/stores/canvas'

export const getInitialElements = (): CanvasElement[] => {
  return [
    {
      id: 'marquee-app-label',
      type: 'text',
      x: 0,
      y: 0,
      text: 'Marquee App: 450x95px',
      fontSize: 11,
      fill: '#74767cff',
      fontFamily: 'Sans',
      align: 'left',
    },
    {
      id: 'marquee-edit-button',
      type: 'text',
      x: 146.7,
      y: 2.9,
      text: 'Edit',
      fontSize: 11,
      fontFamily: 'Sans',
      fill: '#0053e2',
      align: 'left',
    },
    {
      id: 'marquee-app-background',
      type: 'rect',
      x: 0,
      y: 16,
      width: 450,
      height: 95,
      fill: '#ffffff',
    },
    {
      id: 'marquee-app-image',
      type: 'image',
      x: 225, // Position in your visible frame
      y: 16,
      width: 225, // Size of visible area
      height: 95,
      image: '/image.png',
      crop: {
        x: 100, // Start cropping from X=100 on original image
        y: 355, // Start cropping from Y=355 on original image
        width: 2811, // Crop width on original image
        height: 1187, // Crop height on original image
      },
    },
    {
      id: 'marquee-app-headline',
      type: 'text',
      x: 13,
      y: 47,
      text: 'Headline goes here',
      fontSize: 11,
      fontFamily: 'Sans',
      fontStyle: 'bold',
      fill: '#001e60',
      align: 'left',
    },
    {
      id: 'marquee-app-logo',
      type: 'image',
      x: 13,
      y: 29,
      width: 54,
      height: 10.63,
      image: '/logo.png',
    },
    {
      id: 'marquee-app-cta-background',
      type: 'rect',
      x: 13.5,
      y: 79,
      width: 55,
      height: 18,
      cornerRadius: 9,
      strokeColor: '#001e60',
      fill: '#ffffffff',
      strokeWidth: 0.6,
    },
    {
      id: 'marquee-app-ctatext',
      type: 'text',
      x: 22,
      y: 86,
      text: 'CTA button',
      fontSize: 6.5,
      fontFamily: 'Sans',
      fill: '#001e60',
      align: 'center',
    },
    {
      id: 'marquee-app-label',
      type: 'text',
      x: 0,
      y: 0,
      text: 'Marquee App: 450x95px',
      fontSize: 11,
      fill: '#74767cff',
      fontFamily: 'Sans',
      align: 'left',
    },
    {
      id: 'marquee-edit-button',
      type: 'button',
      x: 146.7,
      y: 2.9,
      text: 'Edit',
      fontSize: 11,
      fontFamily: 'Sans',
      fill: '#0053e2',
      align: 'left',
    },
    {
      id: 'marquee-app-background',
      type: 'rect',
      x: 0,
      y: 16,
      width: 450,
      height: 95,
      fill: '#ffffff',
    },
    {
      id: 'marquee-app-image',
      type: 'image',
      x: 225,
      y: 16,
      width: 225,
      height: 95,
      image: '/image.png',
      crop: {
        x: 100,
        y: 355,
        width: 2811,
        height: 1187,
      },
    },
    {
      id: 'marquee-app-headline',
      type: 'text',
      x: 13,
      y: 47,
      text: 'Headline goes here',
      fontSize: 11,
      fontFamily: 'Sans',
      fontStyle: 'bold',
      fill: '#001e60',
      align: 'left',
    },
    {
      id: 'marquee-app-logo',
      type: 'image',
      x: 13,
      y: 29,
      width: 54,
      height: 10.63,
      image: '/logo.png',
    },
    {
      id: 'marquee-app-cta-background',
      type: 'rect',
      x: 13.5,
      y: 79,
      width: 55,
      height: 18,
      cornerRadius: 9,
      strokeColor: '#001e60',
      fill: '#ffffffff',
      strokeWidth: 0.6,
    },
    {
      id: 'marquee-app-ctatext',
      type: 'text',
      x: 13.5,
      y: 79,
      width: 55,
      height: 18,
      text: 'CTA button',
      fontSize: 6.5,
      fontFamily: 'Sans',
      fill: '#001e60',
      align: 'center',
      wrap: 'none',
      verticalAlign: 'middle',
    },
    {
      id: 'marquee-app-disclaimer',
      type: 'text',
      x: 229,
      y: 104,
      width: 220,
      height: 6,
      text: 'This is placeholder disclaimer text and does not constitute legal advice. Use at your own risk.',
      fontSize: 4.6,
      fontFamily: 'Sans',
      fill: '#ffffff',
      align: 'right',
      wrap: 'none',
    },

    // Brandbox Desktop elements (new)
    {
      id: 'brandbox-desktop-label',
      type: 'text',
      x: 0,
      y: 117,
      text: 'Brandbox Desktop: 245x117',
      fontSize: 11,
      fill: '#74767c',
      fontFamily: 'Sans',
      align: 'left',
    },
    {
      id: 'brandbox-desktop-edit-button',
      type: 'button',
      x: 166,
      y: 117,
      text: 'Edit',
      fontSize: 11,
      fontFamily: 'Sans',
      fill: '#0053e2',
      align: 'left',
    },
    {
      id: 'brandbox-desktop-background',
      type: 'rect',
      x: 0,
      y: 132,
      width: 245,
      height: 118,
      fill: '#ffffff',
    },
    {
      id: 'brandbox-desktop-image',
      type: 'image',
      x: 0, // Position in visible frame
      y: 132,
      width: 245, // Size in visible frame
      height: 47,
      image: '/image.png',
      crop: {
        x: 15, // Start cropping from X=15 on original image
        y: 459.3, // Start cropping from Y=459.3 on original image
        width: 2440, // Crop width on original (will be scaled down)
        height: 470, // Crop height on original (will be scaled down)
      },
    },
    {
      id: 'brandbox-desktop-logo',
      type: 'image',
      x: 185,
      y: 198,
      width: 52,
      height: 10.2,
      image: '/logo.png',
    },
    {
      id: 'brandbox-desktop-headline',
      type: 'text',
      x: 8,
      y: 204,
      text: 'Headline goes here',
      fontSize: 7.5,
      fontFamily: 'Sans',
      fontStyle: 'bold',
      fill: '#001e60',
      align: 'left',
    },
    {
      id: 'brandbox-desktop-subhead',
      type: 'text',
      x: 8,
      y: 214,
      text: 'Your subhead goes here',
      fontSize: 5.4,
      fontFamily: 'Sans',
      fill: '#001e60',
      align: 'left',
    },
    {
      id: 'brandbox-desktop-cta-background',
      type: 'rect',
      x: 8.4,
      y: 224.5,
      width: 49,
      height: 16,
      cornerRadius: 8,
      strokeColor: '#001e60',
      fill: '#ffffffff',
      strokeWidth: 0.54,
    },
    {
      id: 'brandbox-desktop-ctatext',
      type: 'text',
      x: 8.4,
      y: 224.5,
      text: 'CTA button',
      fontSize: 5.8,
      fontFamily: 'Sans',
      fill: '#001e60',
      align: 'center',
      width: 49,
      height: 16,
      wrap: 'none',
      verticalAlign: 'middle',
    },
    {
      id: 'brandbox-desktop-disclaimer',
      type: 'text',
      x: 22,
      y: 172,
      width: 220,
      height: 6,
      text: 'This is placeholder disclaimer text and does not constitute legal advice. Use at your own risk.',
      fontSize: 4.6,
      fontFamily: 'Sans',
      fill: '#ffffff',
      align: 'right',
      wrap: 'none',
    },
  ]
}
